version: '3.8'

services:
  postgresql-db:
    image: postgres:16-alpine
    container_name: kt-postgresql-db
    env_file:
      - .env
    ports:
      - "5454:5432"
    volumes:
      - kt-jab-houy-pgdata-v16:/var/lib/postgresql/data
    networks:
      - kt-network

volumes:
  kt-jab-houy-pgdata-v16:

networks:
  kt-network:
    external: true