version: '3.8'

services:
  postgresql-db:
    image: postgres:16-alpine
    container_name: kt-postgresql-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5454:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - kt-network

networks:
  kt-network:
    external: true